Desaprendiendo/Controllers/CategoriaFrontController.cs
using Desaprendiendo.Models.DomainModel;
using Desaprendiendo.Services.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Desaprendiendo.Controllers
{
    public class CategoriaFrontController : Controller
    {

        private readonly ICategoriaRepository _categoriaRepository;
        private readonly IGenericPhotoRepository<Categoria> _repositorioFotos;

        public CategoriaFrontController(ICategoriaRepository categoriaRepository, IGenericPhotoRepository<Categoria> repositorioFotos)
        {
            this._categoriaRepository = categoriaRepository;
            this._repositorioFotos = repositorioFotos;
        }

        // GET: CategoriaFront
        public async Task<IActionResult> Index()
        {
            return View(await _categoriaRepository.GetAll().ToArrayAsync());
        }

        public async Task<IActionResult> Tripartita()
        {
            return await Task.Run(() => View());
        }

        public async Task<IActionResult> Nosotros()
        {
            return await Task.Run(() => View());
        }
        public async Task<IActionResult> Metodologia()
        {
            return await Task.Run(() => View());
        }

        [ResponseCache(Duration = 3600,VaryByHeader ="Id")]
        public FileContentResult GetImgMiniatura(int id)
        {
            return _repositorioFotos.GetImg<Categoria>(id, Sizes.pequeño);
        }
        [ResponseCache(Duration = 3600, VaryByHeader = "Id")]
        public FileContentResult GetImgGrande(int id)
        {
            return _repositorioFotos.GetImg<Categoria>(id, Sizes.grande);
        }

        
    }
}

Desaprendiendo/Controllers/SearchResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Desaprendiendo.Services.Repository;
using Desaprendiendo.Services.SearchService.Model;
using Desaprendiendo.Services.SearchService;

namespace Desaprendiendo.Controllers
{
    public class SearchResultsController : Controller
    {
        private readonly ISearchService _searchService;

        public SearchResultsController(ISubCategoriaRepository repositorioSubCategoria, ICursoRepository repositorioCursos, IModuloRepository repositorioModulos, ICategoriaRepository categoriaRepository)
        {
            _searchService = new SearchService(categoriaRepository, repositorioSubCategoria, repositorioCursos, repositorioModulos);
        }

        // GET: SearchResults
        public async Task<IActionResult> Index(SearchInput textSearched)
        {
            return View(await _searchService.Search(textSearched.SearchedText));
        }

    }
}

Desaprendiendo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="MenuPrincipal">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" asp-controller="CategoriaFront" asp-action="Index">
                <img src="~/images/desaprendiendo.jpg" alt="el logo de la compañia" class="img-responsive" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link elementoMenu" id="Categoria-item" asp-area="" asp-controller="CategoriaFront" asp-action="Index">Categorias&nbsp;|&nbsp;</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link elementoMenu" id="Tripartita-item" asp-area="" asp-controller="CategoriaFront" asp-action="Tripartita">Tripartita&nbsp;|&nbsp;</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link elementoMenu" id="Metodologia-item" asp-area="" asp-controller="CategoriaFront" asp-action="Metodologia">Metodología&nbsp;|&nbsp;</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link elementoMenu" id="Nosotros-item" asp-area="" asp-controller="CategoriaFront" asp-action="Nosotros">Nosotros</a>
                    </li>
                </ul>


            <form class="form-inline my-2 my-lg-0" asp-controller="SearchResults" asp-action="Index" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    @Html.TextBox("searchedText")

                    @*<input class="form-control mr-sm-2" id="searchedText " name="searchedText " type="search" placeholder="Búsqueda" aria-label="Búsqueda">*@
                    <button class="btn btn-outline-success my-2 my-sm-0 elementoPantallaSeleccionable" type="submit">Búsqueda</button>
                </div>
            </form>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top card-footer text-muted">
        <div class="container">
            &copy; 2019 - -Desaprendiendo - <a asp-area="" asp-controller="CategoriaFront" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="~/css/BreadCum.css" />
    @RenderSection("Scripts", required: false)




    <script type="text/javascript">
        var acc = document.getElementsByClassName("accordion");
        var i;

        for (i = 0; i < acc.length; i++) {
            acc[i].addEventListener("click", function () {
                /* Toggle between adding and removing the "active" class,
                to highlight the button that controls the panel */
                this.classList.toggle("active");

                /* Toggle between hiding and showing the active panel */
                var panel = this.nextElementSibling;
                if (panel.style.display === "block") {
                    panel.style.display = "none";
                } else {
                    panel.style.display = "block";
                }
            });
        }
    </script>


</body>
</html>

Desaprendiendo/Views/Shared/_LayoutCursos.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <style type="text/css">
        .bs-example {
            margin: 20px;
        }

        .panel-title .glyphicon {
            font-size: 14px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top overrides">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Desaprendiendo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="color: white;">
                    <li><a asp-area="" asp-controller="Cursos" asp-action="Index">Cursos</a></li>
                    <li><a asp-area="" asp-controller="SubCategorias" asp-action="Index">SubCategorias</a></li>
                    <li><a asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a></li>
                    <li><a asp-area="" asp-controller="Lecciones" asp-action="Index">Lecciones</a></li>
                    <li><a asp-area="" asp-controller="Modulos" asp-action="Index">Modulos</a></li>
                    <li><a asp-area="" asp-controller="AMedidas" asp-action="Index">Cursos a Medida</a></li>
                    <li><a asp-area="" asp-controller="CategoriaFront" asp-action="Index">Front </a></li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Desaprendiendo</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
    <link href="~/Content/themes/base/all.css" rel="stylesheet" />
    <link href="~/Content/themes/base/accordion.css" rel="stylesheet" />
    <link href="~/Content/demos.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript">
        var acc = document.getElementsByClassName("accordion");
        var i;

        for (i = 0; i < acc.length; i++) {
            acc[i].addEventListener("click", function () {
                /* Toggle between adding and removing the "active" class,
                to highlight the button that controls the panel */
                this.classList.toggle("active");

                /* Toggle between hiding and showing the active panel */
                var panel = this.nextElementSibling;
                if (panel.style.display === "block") {
                    panel.style.display = "none";
                } else {
                    panel.style.display = "block";
                }
            });
        }
    </script>
</body>
</html>

Desaprendiendo/Views/Shared/_LayoutNew.cshtml
@using Desaprendiendo.Views.ViewComponents.ViewModels.Menu
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<header>
    <nav>
        @await Component.InvokeAsync("MenuComponent")
    </nav>
</header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top card-footer text-muted">
        <div class="container">
            &copy; 2019 - -Desaprendiendo - <a asp-area="" asp-controller="CategoriaFront" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="~/css/BreadCum.css" />
    @RenderSection("Scripts", required: false)




    <script type="text/javascript">
        var acc = document.getElementsByClassName("accordion");
        var i;

        for (i = 0; i < acc.length; i++) {
            acc[i].addEventListener("click", function () {
                /* Toggle between adding and removing the "active" class,
                to highlight the button that controls the panel */
                this.classList.toggle("active");

                /* Toggle between hiding and showing the active panel */
                var panel = this.nextElementSibling;
                if (panel.style.display === "block") {
                    panel.style.display = "none";
                } else {
                    panel.style.display = "block";
                }
            });
        }
    </script>


</body>
</html>

Desaprendiendo/Views/Shared/_LeccionesPorModulo.cshtml
@model IEnumerable<Desaprendiendo.Models.DomainModel.Lección>

<div id="comments-tool">
     @foreach (var item in Model)
     {
            <div>
                <div >
                    From:

                    @Html.DisplayFor(modelItem => item.Lección1)
                </div>
                <div >
                    @Html.CheckBox("Like", (bool)item.HayEjercicios)
                </div>
                <div >
                    @Html.DisplayFor(modelItem => item.ComentarioHtml)
                </div>
                <hr>
            </div>

        }
    </div>

}